###
POST {{base_url}}/api/events
Content-Type: application/json

< ./test-data/incident.json

###
POST {{base_url}}/api/events
Content-Type: application/json

< ./test-data/maintenance.json

###
GET {{base_url}}/api/events

###
GET {{base_url}}/api/events/M-128737
