###
POST localhost:8080/api/events
Content-Type: application/json

< ./test-data/incident.json

###
POST localhost:8080/api/events
Content-Type: application/json

< ./test-data/maintenance.json

###
GET localhost:8080/api/events

###
GET localhost:8080/api/events/M-128737
