# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - status-page

on:
  push:
    branches:
      - build-test
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      #     - name: NodeJS Setup
      #       uses: actions/setup-node@v3
      #       with:
      #         node-version: 20
      #         cache: 'npm'
      #         cache-dependency-path: '**/package-lock.json'
      
      #     - name: npm install and build
      #       working-directory: ./src/main/angular
      #       run: |
      #         npm install
      #         npm run build
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'
